[snowflake]
account = "XVAQISC-ZJ84196"
warehouse = "COMPUTE_WH"
database = "TPCDS"
schema = "RAW"
table = "inventory"
user = "Proffaj"
role = "accountadmin"
stage_name = "inv_Stage"

[s3]
url = "https://de-materials-tpcds.s3.ca-central-1.amazonaws.com/inventory.csv"
destination_folder = "/tmp"
file_name = "inventory.csv"
local_file_path = "/tmp/inventory.csv"
